project:
  type: book

book:
  title: "Statistical Machine Learning (208 @ LU) Notes"
  author: "Abhishek Chakraborty"
  date: today
  date-format: long
  reader-mode: true
  
  page-footer:
    left: |
      Statistical Machine Learning (208) Course Notes by Abhishek Chakraborty.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  chapters:
    - index.qmd
    - Slides1.qmd
    - Slides2.qmd
    - Slides3.qmd
    - Slides4.qmd
    - Slides5.qmd
    - Slides6.qmd
    - Slides8.qmd
    - Slides9.qmd
    - Slides10.qmd
    

        
        
#    - intro.qmd
#    - summary.qmd
#    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt


